/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * @author Akira Hanada
 */
package UserInterface.WorkAreas.AdminRole.ManageFacultyWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.FacultyDirectory;
import Business.Profiles.FacultyProfile;

import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akira Hanada
 */
public class ManageFacultyJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    FacultyProfile selectedFaculty;

    /**
     * Creates new form ManageFacultyJPanel
     */
    public ManageFacultyJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        refreshTable();
    }

    /**
     * Refresh the faculty table with current data
     * @author Akira Hanada
     */
    public void refreshTable() {
        FacultyDirectory fd = business.getFacultyDirectory();
        
        DefaultTableModel model = (DefaultTableModel) FacultyTable.getModel();
        model.setRowCount(0);
        
        for (FacultyProfile faculty : fd.getFacultyList()) {
            Person person = faculty.getPerson();
            
            Object[] row = new Object[8];
            row[0] = faculty;
            row[1] = person.getPersonId();
            row[2] = person.getName();
            row[3] = person.getEmail();
            row[4] = person.getPhone();
            row[5] = person.getAddress();
            row[6] = faculty.getDepartment();
            row[7] = faculty.getSpecialization();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FacultyTable = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        ViewEditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Manage Faculty Records");

        FacultyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faculty", "Person ID", "Name", "Email", "Phone", "Address", "Department", "Specialization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FacultyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FacultyTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(FacultyTable);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        ViewEditButton.setBackground(new java.awt.Color(51, 153, 255));
        ViewEditButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ViewEditButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewEditButton.setText("View / Edit");
        ViewEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEditButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(255, 51, 51));
        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewEditButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(ViewEditButton)
                    .addComponent(DeleteButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // Navigate back to admin dashboard
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void FacultyTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacultyTableMousePressed
        // Handle row selection - Author: Akira Hanada
        int selectedRow = FacultyTable.getSelectedRow();
        if (selectedRow >= 0) {
            selectedFaculty = (FacultyProfile) FacultyTable.getValueAt(selectedRow, 0);
        }
    }//GEN-LAST:event_FacultyTableMousePressed

    private void ViewEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEditButtonActionPerformed
        // Navigate to faculty profile editor - Author: Akira Hanada
        if (selectedFaculty == null) {
            JOptionPane.showMessageDialog(this, 
                "Please select a faculty member from the table.", 
                "No Selection", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        AdministerFacultyJPanel afp = new AdministerFacultyJPanel(business, CardSequencePanel, selectedFaculty, this);
        CardSequencePanel.add("Administer Faculty", afp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_ViewEditButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // Delete selected faculty - Author: Akira Hanada
        if (selectedFaculty == null) {
            JOptionPane.showMessageDialog(this, 
                "Please select a faculty member to delete.", 
                "No Selection", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this faculty member?\n" +
            "Name: " + selectedFaculty.getPerson().getName() + "\n" +
            "Person ID: " + selectedFaculty.getPerson().getPersonId(),
            "Confirm Delete", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            FacultyDirectory fd = business.getFacultyDirectory();
            boolean success = fd.deleteFaculty(selectedFaculty.getPerson().getPersonId());
            
            if (success) {
                JOptionPane.showMessageDialog(this, 
                    "Faculty member deleted successfully!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                selectedFaculty = null;
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Failed to delete faculty member.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTable FacultyTable;
    private javax.swing.JButton ViewEditButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
