/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * @author Akira Hanada
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;

import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author Akira Hanada
 */
public class AdministerPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Person selectedPerson;
    ManagePersonsJPanel parentPanel;

    public AdministerPersonJPanel(Business bz, JPanel jp, Person person, ManagePersonsJPanel parent) {

        CardSequencePanel = jp;
        this.business = bz;
        this.selectedPerson = person;
        this.parentPanel = parent;
        initComponents();
        
        if (selectedPerson != null) {
            populateFields();
        }
    }

    /**
     * Populate form fields with person data
     * @author Akira Hanada
     */
    private void populateFields() {
        if (selectedPerson != null) {
            PersonIDTextField.setText(selectedPerson.getPersonId());
            NameTextField.setText(selectedPerson.getName());
            EmailTextField.setText(selectedPerson.getEmail());
            PhoneTextField.setText(selectedPerson.getPhone());
            AddressTextArea.setText(selectedPerson.getAddress());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PersonIDTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        PhoneTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTextArea = new javax.swing.JTextArea();
        SaveButton = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Person Profile");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Person ID:");
        add(jLabel3);
        jLabel3.setBounds(30, 70, 100, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Name:");
        add(jLabel4);
        jLabel4.setBounds(30, 100, 100, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Email:");
        add(jLabel5);
        jLabel5.setBounds(30, 130, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Phone:");
        add(jLabel6);
        jLabel6.setBounds(30, 160, 100, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Address:");
        add(jLabel7);
        jLabel7.setBounds(30, 190, 100, 20);

        PersonIDTextField.setEditable(false);
        PersonIDTextField.setBackground(new java.awt.Color(240, 240, 240));
        add(PersonIDTextField);
        PersonIDTextField.setBounds(140, 70, 300, 25);

        add(NameTextField);
        NameTextField.setBounds(140, 100, 300, 25);

        add(EmailTextField);
        EmailTextField.setBounds(140, 130, 300, 25);

        add(PhoneTextField);
        PhoneTextField.setBounds(140, 160, 300, 25);

        AddressTextArea.setColumns(20);
        AddressTextArea.setRows(3);
        jScrollPane1.setViewportView(AddressTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(140, 190, 300, 60);

        SaveButton.setBackground(new java.awt.Color(51, 153, 255));
        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        add(SaveButton);
        SaveButton.setBounds(370, 270, 70, 32);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(30, 270, 76, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // Navigate back to person list
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // Save person profile - Author: Akira Hanada
        
        // Validate inputs
        String name = NameTextField.getText();
        String email = EmailTextField.getText();
        String phone = PhoneTextField.getText();
        String address = AddressTextArea.getText();
        
        if (name == null || name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (email == null || email.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Basic email validation
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Update person information
            if (selectedPerson != null) {
                selectedPerson.setName(name.trim());
                selectedPerson.setEmail(email.trim());
                selectedPerson.setPhone(phone.trim());
                selectedPerson.setAddress(address.trim());
                
                JOptionPane.showMessageDialog(this, 
                    "Person profile updated successfully!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
            
            // Refresh parent table - Author: Akira Hanada
            if (parentPanel != null) {
                parentPanel.refreshTable();
            }
            
            // Navigate back
            CardSequencePanel.remove(this);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error updating person profile: " + e.getMessage(), 
                "Update Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JButton Back;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PersonIDTextField;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
