/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * @author Akira Hanada
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.EmployeeDirectory;
import Business.Profiles.EmployeeProfile;
import Business.Profiles.FacultyDirectory;
import Business.Profiles.FacultyProfile;
import Business.Profiles.Profile;
import Business.Profiles.StudentDirectory;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccountDirectory;

import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author Akira Hanada
 */
public class CreateUserAccountJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    ManageUserAccountsJPanel parentPanel;

    public CreateUserAccountJPanel(Business bz, JPanel jp, ManageUserAccountsJPanel parent) {
        CardSequencePanel = jp;
        this.business = bz;
        this.parentPanel = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: DO NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PhoneTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        BackButton.setText("<< Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton);
        BackButton.setBounds(40, 420, 100, 32);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Create User Account");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 29);

        CreateButton.setBackground(new java.awt.Color(51, 153, 51));
        CreateButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });
        add(CreateButton);
        CreateButton.setBounds(330, 420, 100, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Username:");
        add(jLabel3);
        jLabel3.setBounds(40, 70, 120, 16);
        add(UsernameTextField);
        UsernameTextField.setBounds(180, 70, 250, 35);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Name:");
        add(jLabel4);
        jLabel4.setBounds(40, 115, 120, 16);
        add(NameTextField);
        NameTextField.setBounds(180, 115, 250, 35);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Email:");
        add(jLabel5);
        jLabel5.setBounds(40, 160, 120, 16);
        add(EmailTextField);
        EmailTextField.setBounds(180, 160, 250, 35);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Phone:");
        add(jLabel6);
        jLabel6.setBounds(40, 205, 120, 16);
        add(PhoneTextField);
        PhoneTextField.setBounds(180, 205, 250, 35);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Password:");
        add(jLabel7);
        jLabel7.setBounds(40, 250, 120, 16);
        add(PasswordTextField);
        PasswordTextField.setBounds(180, 250, 250, 35);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Role:");
        add(jLabel8);
        jLabel8.setBounds(40, 295, 120, 16);

        RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Admin", "Faculty", "Student" }));
        add(RoleComboBox);
        RoleComboBox.setBounds(180, 295, 250, 35);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Address:");
        add(jLabel9);
        jLabel9.setBounds(40, 340, 120, 16);

        AddressTextArea.setColumns(20);
        AddressTextArea.setRows(3);
        jScrollPane1.setViewportView(AddressTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(180, 340, 250, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // Navigate back to user accounts list
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // Create new user account - Author: Akira Hanada
        
        // Validate inputs
        String username = UsernameTextField.getText();
        String name = NameTextField.getText();
        String email = EmailTextField.getText();
        String phone = PhoneTextField.getText();
        String password = new String(PasswordTextField.getPassword());
        String role = (String) RoleComboBox.getSelectedItem();
        String address = AddressTextArea.getText();
        
        if (username == null || username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (name == null || name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (email == null || email.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Basic email validation
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (password == null || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (password.length() < 6) {
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (role == null || role.equals("Select Role")) {
            JOptionPane.showMessageDialog(this, "Please select a role.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if username already exists
        UserAccountDirectory uad = business.getUserAccountDirectory();
        if (uad.findByUsername(username.trim()) != null) {
            JOptionPane.showMessageDialog(this, 
                "Username already exists. Please choose a different username.", 
                "Duplicate Username", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Create person
            PersonDirectory pd = business.getPersonDirectory();
            Person person = pd.newPerson(name.trim());
            person.setEmail(email.trim());
            person.setPhone(phone.trim());
            person.setAddress(address.trim());
            
            // Create profile based on role
            Profile profile = null;
            switch (role) {
                case "Admin":
                    EmployeeDirectory ed = business.getEmployeeDirectory();
                    EmployeeProfile ep = ed.newEmployeeProfile(person);
                    profile = ep;
                    break;
                case "Faculty":
                    FacultyDirectory fd = business.getFacultyDirectory();
                    FacultyProfile fp = fd.newFacultyProfile(person);
                    profile = fp;
                    break;
                case "Student":
                    StudentDirectory sd = business.getStudentDirectory();
                    StudentProfile sp = sd.newStudentProfile(person);
                    profile = sp;
                    break;
            }
            
            if (profile == null) {
                JOptionPane.showMessageDialog(this, 
                    "Failed to create profile.", 
                    "Creation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Create user account
            uad.newUserAccount(profile, username.trim(), password);
            
            JOptionPane.showMessageDialog(this, 
                "User account created successfully!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Refresh parent table and navigate back
            if (parentPanel != null) {
                parentPanel.refreshTable();
            }
            CardSequencePanel.remove(this);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error creating user account: " + e.getMessage(), 
                "Creation Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CreateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JComboBox<String> RoleComboBox;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
